name: test

train:
  steps: 1000
  image_size: 64
  image_channels: 3
  lr: 0.0001
  beta: [0.0001, 0.02]    # start, end
  batch: 64
  epochs: 10
  save_period: 5
  sample_period: 1

inf:
  steps: 500
  num_images: 32

model:
  base_channels: 64
  timestep_embed_dims: 64
  timestep_proj_dims: 256
  layers: 2

device: "cuda:1"
clip: 1.0